### ISSUE TITLE
[Bug] Minor bug? with stamp returns

### ISSUE THREAD

**Issue by Context6016** [ProjectAsakura/Bayshore#56]
If you have exactly 4 open slots left on your stamp sheet (as pictured) and you win a stamp return battle with 3 ghosts you'll fill the current sheet and move to the next one but you'll keep all your current stamps minus 4 (It'll start out with all stamps filled except the last 4 spaces)

![Untitled](https://user-images.githubusercontent.com/113903301/210450274-8004eccd-e4d4-4550-bb15-2f06ecf292d5.png)

**Comment by ry00001** [comment]
Thank you for reporting this, I'll make sure this is looked at.

**Comment by shiroikitsu8** [comment]
Try again.. it should be fixed

**Comment by ry00001** [comment]
I have not heard anything from anyone about this bug so I can only assume it is fixed. Please re-open an issue or reach out to me via other means if it is not.
