### ISSUE TITLE
Using non-standard licnese

### ISSUE THREAD

**Issue by GXTX** [ProjectAsakura/Bayshore#69]
Consider changing to MIT or similar.

The use of a non-standard license makes it difficult to know what my rights are in regards to the program, and potentially stops developers from contributing due to both the confusing terms, and the terms being untested.

**Comment by ry00001** [comment]
This license was put in place to prevent code theft by notorious code theft group TeknoGods.

Given how code theft has occurred anyway (huge parts of their WMMT6 server project are based on this project, without my permission), it didn't really do much.

We are open to relicensing.
