### ISSUE TITLE
where is config.json in bayshore

### ISSUE THREAD

**Issue by bukandin** [ProjectAsakura/Bayshore#75]
Step 4: Setting up Bayshore itself
Clone Bayshore's repository into a directory of your choice.
Afterwards, copy config.example.json to config.json, and open it in your favourite text editor.
Change its contents to match your environment.
Then, run yarn install to install the necessary dependencies, and then yarn build_protos to compile the game's networking definitions.

i found config.example.json but I never found config.json so how can i solve this ? and what does it mean change its contents to match ur environment.

**Comment by ry00001** [comment]
> Afterwards, copy config.example.json to config.json
Basic reading skill is required to use this software.
